### ISSUE TITLE
suggestion: 点赞功能

### ISSUE THREAD

**Issue by vxst** [lingsamuel/purity#1]
或许应该增加点赞功能？经常会觉得文章写得很好，但不能点赞……

可能的实现方法

 * 写一个aws lambda+用localStorage存续一个首次访问生成的、随机的用户id+DynamoDB，可以几乎免费地完成一个点赞api
 * 直接接[likebtn](https://likebtn.com/)

感觉或许不需要加上邮箱/身份验证什么的，或许有时候只需要让读者能够表达赞赏，让自己知道有多少认可（甚至不一定公开暴露数字），知道具体点赞的人的话反而会变得社交化，可能不是你喜欢的

**Comment by lingsamuel** [comment]
不喜欢外部服务依赖，可能可以通过链接到github的issue实现

**Comment by vxst** [comment]
这样的话会记录身份？

**Comment by lingsamuel** [comment]
🤔 似乎应该把“不要随便添加乱七八糟的第三方服务”也加进[设计理念-Less is More](https://lingsamuel.github.io/page/theme-purity/)一节。
不过点赞这个功能也许不是那么乱七八糟……？

总的来说这个主题还是保持简单简洁为主，不太希望乱七八糟的。但[总之加上了](https://github.com/lingsamuel/purity/blob/2ab11fb4a87145dc280e928708c7b45763603435/layouts/partials/3rd/likebtn.html)。
